using IflyWebApp.Models;

namespace IflyWebApp.Services
{
    /// <summary>
    /// Interface for website generation service
    /// </summary>
    public interface IWebsiteGenerationService
    {
        Task<string> GenerateWebsiteAsync(string templateName, Dictionary<string, string> parameters);
        Task<bool> IsConfiguredAsync();
    }

    /// <summary>
    /// Website generation service that uses securely stored API keys
    /// Demonstrates how to use keys without storing them in web.config
    /// </summary>
    public class WebsiteGenerationService : IWebsiteGenerationService
    {
        private readonly IKeyManagementService _keyManagement;
        private readonly ILogger<WebsiteGenerationService> _logger;
        private readonly HttpClient _httpClient;

        public WebsiteGenerationService(
            IKeyManagementService keyManagement, 
            ILogger<WebsiteGenerationService> logger,
            HttpClient httpClient)
        {
            _keyManagement = keyManagement;
            _logger = logger;
            _httpClient = httpClient;
        }

        public async Task<string> GenerateWebsiteAsync(string templateName, Dictionary<string, string> parameters)
        {
            try
            {
                var keys = await _keyManagement.LoadKeysAsync();
                
                if (string.IsNullOrWhiteSpace(keys.WebsiteGenerationApiKey))
                {
                    throw new InvalidOperationException("Website generation API key is not configured");
                }

                // Simulate website generation with external API
                _logger.LogInformation("Generating website with template: {TemplateName}", templateName);
                
                // Add API key to request headers (secure way)
                _httpClient.DefaultRequestHeaders.Authorization = 
                    new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", keys.WebsiteGenerationApiKey);

                // For demonstration, we'll generate a simple HTML page
                var websiteContent = GenerateStaticWebsite(templateName, parameters);
                
                _logger.LogInformation("Website generated successfully");
                return websiteContent;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to generate website");
                throw;
            }
        }

        public async Task<bool> IsConfiguredAsync()
        {
            var keys = await _keyManagement.LoadKeysAsync();
            return !string.IsNullOrWhiteSpace(keys.WebsiteGenerationApiKey) && 
                   keys.WebsiteGenerationApiKey != "REPLACE_WITH_ACTUAL_API_KEY";
        }

        private string GenerateStaticWebsite(string templateName, Dictionary<string, string> parameters)
        {
            var title = parameters.GetValueOrDefault("title", "Generated Website");
            var content = parameters.GetValueOrDefault("content", "Welcome to your generated website!");
            var theme = parameters.GetValueOrDefault("theme", "default");

            return $@"<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <title>{title}</title>
    <style>
        body {{ 
            font-family: Arial, sans-serif; 
            margin: 0; 
            padding: 20px; 
            background-color: {(theme == "dark" ? "#333" : "#f5f5f5")}; 
            color: {(theme == "dark" ? "#fff" : "#333")};
        }}
        .container {{ 
            max-width: 800px; 
            margin: 0 auto; 
            background: {(theme == "dark" ? "#444" : "white")}; 
            padding: 20px; 
            border-radius: 8px; 
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .header {{ 
            border-bottom: 2px solid #007acc; 
            padding-bottom: 10px; 
            margin-bottom: 20px; 
        }}
        .footer {{ 
            margin-top: 30px; 
            padding-top: 10px; 
            border-top: 1px solid #ddd; 
            text-align: center; 
            font-size: 0.9em; 
            color: #666; 
        }}
    </style>
</head>
<body>
    <div class=""container"">
        <div class=""header"">
            <h1>{title}</h1>
        </div>
        <div class=""content"">
            <p>{content}</p>
            <p><strong>Template:</strong> {templateName}</p>
            <p><strong>Generated:</strong> {DateTime.Now:yyyy-MM-dd HH:mm:ss}</p>
        </div>
        <div class=""footer"">
            <p>Generated by Ifly Website Generator - Keys securely managed!</p>
        </div>
    </div>
</body>
</html>";
        }
    }
}